version: '3.4'

services:
  animalsshelterbackend:
    image: ${DOCKER_REGISTRY-}animalsshelterbackend
    container_name: ShelterBackend
    build:
      context: .
      dockerfile: AnimalsShelterBackend/Dockerfile
    ports:
        - "8080:80"
