version: '3.4'

networks:
  shelter:

services:

  animalsshelterfrontend:
    build:
     context: ../Frontend
     dockerfile: Dockerfile
    networks:
        - shelter
    environment:
        - REACT_APP_API_URL=http://localhost/api

  animalsshelterbackend:
    image: vdd/animalsshelterbackend
    container_name: ShelterBackend
    build:
      context: .
      dockerfile: AnimalsShelterBackend/Dockerfile
    networks:
        - shelter
    ports:
        - "5000:5000"
        - "5001:5001"
    environment:
        - ASPNETCORE_URLS=http://+:5000

  nginx:
    image: nginx:stable-alpine
    ports:
        - "80:80"
    networks:
        - shelter
    depends_on:
        - animalsshelterbackend
        - animalsshelterfrontend
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

  animalsshelterbackendDB:
    image: postgres:latest
    container_name: shelterDB
    networks:
        - shelter
    environment:
        - POSTGRES_DB=AnimalsShelterDB
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Sonic.exe
    volumes:
        - ./.containers/shelter-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  minio:
    image: minio/minio
    container_name: minioStorage
    networks:
        - shelter
    ports:
        - "9000:9000"
        - "9001:9001"
    environment:
         MINIO_ROOT_USER: minioadmin
         MINIO_ROOT_PASSWORD: minioadmin
    volumes:
        - ./.containers/minio-storage:/data
    command: server --console-address ":9001" /data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitMQ
    networks:
        - shelter
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./.containers/rabbitmq:/var/lib/rabbitmq

  redis:
    container_name: redis
    image: redis:latest
    networks:
        - shelter
    ports:
        - 6379:6379
    volumes:
        - ./.containers/redis:/data
    environment:
        REDIS_PASSWORD: redispass
        REDIS_USER: redisuser
        REDIS_USER_PASSWORD: rdp334pas_s

  createbuckets:
    image: minio/mc
    networks:
        - shelter
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin); do
      echo 'Waiting for MinIO...';
      sleep 2;
      done;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing myminio/animalspictures;
      /usr/bin/mc anonymous set public myminio/animalspictures;
      /usr/bin/mc mb --ignore-existing myminio/articlesandnews;
      /usr/bin/mc anonymous set public myminio/articlesandnews;
      /usr/bin/mc mb --ignore-existing myminio/users;
      /usr/bin/mc anonymous set public myminio/users;
      exit 0;
      "
    
    
  
    
